module internal SoloDatabase.RelationsEntity

let internal readMetadataByOwner = RelationsEntitySync.readMetadataByOwner
let internal readMetadataByTarget = RelationsEntitySync.readMetadataByTarget
let internal relationDescriptorByPath = RelationsEntitySync.relationDescriptorByPath
let internal insertTargetEntity = RelationsEntitySync.insertTargetEntity
let internal ensureTargetExists = RelationsEntitySync.ensureTargetExists
let internal readDbRefId = RelationsEntitySync.readDbRefId
let internal tryGetValueOptionValue = RelationsEntitySync.tryGetValueOptionValue
let internal tryGetVOptionProperty = RelationsEntitySync.tryGetVOptionProperty
let internal tryGetPendingEntity = RelationsEntitySync.tryGetPendingEntity
let internal tryGetPendingTypedId = RelationsEntitySync.tryGetPendingTypedId
let internal createDbRefTo = RelationsEntitySync.createDbRefTo
let internal createDbRefLoaded = RelationsEntitySync.createDbRefLoaded
let internal updateDbRefJson = RelationsEntitySync.updateDbRefJson
let internal shouldSyncDbRefJson = RelationsEntitySync.shouldSyncDbRefJson
let internal ensureLinkWriteApplied = RelationsEntitySync.ensureLinkWriteApplied
let internal resolveTypedIdToTargetId = RelationsEntitySync.resolveTypedIdToTargetId
let internal refComparer = RelationsEntityCascade.refComparer
let internal cascadeInsertDeep = RelationsEntityCascade.cascadeInsertDeep
let internal resolveSingleTargetIdAndCascade = RelationsEntityCascade.resolveSingleTargetIdAndCascade
let internal collectManyTargetIdsAndCascade = RelationsEntityCascade.collectManyTargetIdsAndCascade
let internal readSingleIdNoCascade = RelationsEntityCascade.readSingleIdNoCascade
let internal applyOps = RelationsEntityApplyOps.applyOps
