module internal SoloDatabase.RelationsSchema

let internal ensureRelationCatalogTable = RelationsSchemaBuilder.ensureRelationCatalogTable
let internal getSQLForTriggersForTable = RelationsSchemaBuilder.getSQLForTriggersForTable
let internal ensureCollectionMetadataColumn = RelationsSchemaBuilder.ensureCollectionMetadataColumn
let internal ensureCollectionTableExists = RelationsSchemaBuilder.ensureCollectionTableExists
let internal getRelationSpecs = RelationsSchemaValidator.getRelationSpecs
let internal hasManyBackReference = RelationsSchemaValidator.hasManyBackReference
let internal tryGetStoredRelationName = RelationsSchemaBuilder.tryGetStoredRelationName
let internal sqliteTableExistsByName = RelationsSchemaBuilder.sqliteTableExistsByName
type internal MissingReadMetadataState = RelationsSchemaBuilder.MissingReadMetadataState
let internal classifyMissingReadMetadata = RelationsSchemaBuilder.classifyMissingReadMetadata
let internal resolveTargetCollectionName = RelationsSchemaBuilder.resolveTargetCollectionName
let internal buildRelationDescriptors = RelationsSchemaValidator.buildRelationDescriptors
let internal ensureMetadataNotResurrected = RelationsSchemaLinkTableDDL.ensureMetadataNotResurrected
let internal ensureRelationSchema = RelationsSchemaLinkTableDDL.ensureRelationSchema
let internal relationSchemaRequiresEnsure = RelationsSchemaLinkTableDDL.relationSchemaRequiresEnsure
