name: Combined Workflow for .NET Build, Artifact Upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Cache dependencies
      uses: actions/cache@v4.0.2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -o ./build_output
    - name: Test
      run: dotnet test --no-build --verbosity normal -o ./build_output
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: net-build-output
        path: ./build_output/**
        retention-days: 5  # Specify how long to keep the artifact, defaults to 90 days
