name: Build, Test and Upload

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md' # Ignore changes to markdown files for triggering the build
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: github.actor == 'Unconcurrent' || github.actor == 'sologub'
    runs-on: ubuntu-latest # self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Cache NuGet packages and dotnet tools
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.nuget/packages
          ~/.config/dotnet-tools.json
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}-
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./SoloDB/SoloDB/bin/Release/net8.0/*
