name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.gitignore'

permissions:
  contents: read

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    if: github.actor == 'Unconcurrent' || github.actor == 'sologub'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: latest
        dotnet-quality: ga

    - name: Restore
      run: dotnet restore SoloDB/SoloDB.fsproj

    - name: Build
      run: dotnet build SoloDB/SoloDB.fsproj --configuration Release --no-restore '-p:ParallelCompilation='

    - name: Upload NuGet package
      uses: actions/upload-artifact@main
      with:
        name: solodb-nuget-package
        path: SoloDB/bin/Release/*.nupkg
        if-no-files-found: error
